In [1]:
import numpy as np

In [3]:
x = np.arange(10)*2
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
%time for i in range(1000): np.arange(10000000)*2

CPU times: total: 42 s
Wall time: 43.9 s


In [5]:
y = list(range(10))*2
print(y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
%time for i in range(1000): list(range(10000000))*2


CPU times: total: 4.83 s
Wall time: 5.11 s


KeyboardInterrupt: 

In [8]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#Array Transposition

In [9]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [10]:
#create array with 6 rows and 3 cols
#randn draws each element from a standard normall
arr1 = np.random.randn(6,3)
arr1

array([[ 0.08229993,  0.06598197, -0.24263655],
       [ 0.78709372, -0.26850985, -1.32320533],
       [-0.23008012,  0.61466142,  0.12552655],
       [ 1.2770126 ,  0.67368086,  0.24798079],
       [-0.02495212,  0.19740864,  0.45104286],
       [-1.46021117, -0.19924195, -2.24710854]])

In [13]:
#performs a matrixm multiplaction between arr1 and its transpose
np.dot(arr1.T,arr1)

array([[4.4428271 , 0.79897503, 2.49633637],
       [0.79897503, 0.98677326, 1.12025831],
       [2.49633637, 1.12025831, 7.13993269]])

In [15]:
import pandas as pd
pd.Series(['Male','Female','Female','Male','Female'])


0      Male
1    Female
2    Female
3      Male
4    Female
dtype: object

In [17]:
ser = pd.Series(np.array(['Male','Female','Female','Male','Female']))
ser.values

array(['Male', 'Female', 'Female', 'Male', 'Female'], dtype=object)

In [19]:
dict_data = { 'a':0,'b':1,'c':2}
pd.Series(dict_data)

a    0
b    1
c    2
dtype: int64

In [21]:
ser1 = pd.Series(dict_data)
type(ser1)

pandas.core.series.Series

In [22]:
ser1.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
list_data = ['2019-01-01',3.14,'Hello World',None,True]
ser2 = pd.Series(list_data) 
ser2

RangeIndex(start=0, stop=5, step=1)

In [26]:
ser2.index

RangeIndex(start=0, stop=5, step=1)

In [34]:
e = pd.DataFrame({
    "Name":['Braund','Mr Owen','Mr Harrison','Mr Allen'],
    "Age":[22,35,28,19],
    "Sex":["male","male","male","female"]
})
e['Name']

0         Braund
1        Mr Owen
2    Mr Harrison
3       Mr Allen
Name: Name, dtype: object

In [36]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,0]])

In [38]:
df.columns  

RangeIndex(start=0, stop=3, step=1)

In [40]:
my_index = ['a','b','c']
my_values = [222,333,444]
my_dict = {'a':222,'b':333,'c':444}
my_arr = np.array(my_values)
my_arr

array([222, 333, 444])

In [43]:
#builds a pandas series from the list 
pd.Series(my_values)  

0    222
1    333
2    444
dtype: int64

In [45]:
#creates a series using your custom index
pd.Series(data=my_values,index=my_index)

a    222
b    333
c    444
dtype: int64

In [47]:
#series from a numpy array 
pd.Series(my_arr)

0    222
1    333
2    444
dtype: int64

In [48]:
#series from a numpy array with custom index
pd.Series(data=my_arr,index=my_index)

a    222
b    333
c    444
dtype: int64

In [49]:
#series from a dictionary
pd.Series(my_dict)

a    222
b    333
c    444
dtype: int64

In [51]:
s = pd.Series(data = [111,222,333,444], index=['a','b','c','d'],name = 'MySeries')
s

a    111
b    222
c    333
d    444
Name: MySeries, dtype: int64

In [53]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [54]:
s.name

'MySeries'

In [55]:
s.dtype

dtype('int64')

In [57]:
s.values

array([111, 222, 333, 444])

In [59]:
s[1]

C:\Users\vedas\AppData\Local\Temp\ipykernel_21240\878419959.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]


np.int64(222)

In [60]:
s[0]

C:\Users\vedas\AppData\Local\Temp\ipykernel_21240\243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


np.int64(111)

In [62]:
s.iloc[2]

np.int64(333)

In [64]:
s[2:4]

c    333
d    444
Name: MySeries, dtype: int64

In [66]:
s[['a','c']]

a    111
c    333
Name: MySeries, dtype: int64

In [70]:
s1  = pd.Series([1,2,3,4], index=['d','b','c','a'])
s2  = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(s1)
print(s2)

d    1
b    2
c    3
a    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [71]:
s1 + s2

a    5
b    4
c    6
d    5
dtype: int64

In [73]:
s1 - s2

a    3
b    0
c    0
d   -3
dtype: int64

In [74]:
s1 * s2

a    4
b    4
c    9
d    4
dtype: int64

In [75]:
s1 / s2

a    4.00
b    1.00
c    1.00
d    0.25
dtype: float64

In [76]:
2* s1

d    2
b    4
c    6
a    8
dtype: int64

In [77]:
s1.sum()

np.int64(10)

In [78]:
s1.mean()

np.float64(2.5)

In [79]:
s1.median()

np.float64(2.5)

In [84]:
s1.std()

np.float64(1.2909944487358056)

In [81]:
s1.sort_index()

a    4
b    2
c    3
d    1
dtype: int64

In [82]:
s1.sort_values()

d    1
b    2
c    3
a    4
dtype: int64

In [88]:
ser_height = pd.Series([165.3,170.1,175,182,167.1,180,162.2,168.3,169.2,158.2,176,160,161,162,173,180.1,140,120,179,193,184])
ser_height

0     165.3
1     170.1
2     175.0
3     182.0
4     167.1
5     180.0
6     162.2
7     168.3
8     169.2
9     158.2
10    176.0
11    160.0
12    161.0
13    162.0
14    173.0
15    180.1
16    140.0
17    120.0
18    179.0
19    193.0
20    184.0
dtype: float64

In [89]:
ser_height.apply(lambda x: x/100)


0     1.653
1     1.701
2     1.750
3     1.820
4     1.671
5     1.800
6     1.622
7     1.683
8     1.692
9     1.582
10    1.760
11    1.600
12    1.610
13    1.620
14    1.730
15    1.801
16    1.400
17    1.200
18    1.790
19    1.930
20    1.840
dtype: float64

In [ ]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
ser3 = pd.Series(sdata)

In [ ]:
states = ['California','Ohio','Oregon','Texas']
obj2 = pd.Series(sdata,index=states)
obj2

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [93]:
pd.isnull(obj2)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [95]:
pd.notnull(obj2) 

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [98]:
obj2.name = "population"
obj2.index.name = "state"
obj2

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [100]:
obj1 = {}

In [107]:
#1. Create examples of zero vector, one vector, square matrix, diagonal matrix, identity matrix, and symmetric matrix one by one, and represent vectors and matrices with NumPy.
zero_arr = np.zeros(5)  
one_arr = np.ones(5)
square_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
diag_mat = np.diag([1,2,3])
identity_mat = np.eye(4)
symmetric_mat = np.array([[1,2,3],[2,4,5],[3,5,6]])
print(zero_arr)
print(one_arr)
print(square_mat)
print(diag_mat)
print(identity_mat)
print(symmetric_mat)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 2 3]
 [2 4 5]
 [3 5 6]]


In [108]:
"""2. The shares of three companies A, B, and C are 1 million won, 800,000 won, and 500,000 won, respectively. We want to find the amount required to purchase 3, 4, and 5 shares of these stocks, respectively.

i)       Express the stocks’ price and quantity as p vector and n vector, respectively and coded with NumPy.


ii)       The amount required to purchase stocks is expressed by multiplication, and the value is calculated by Numpy operation.

Samsung Innovation Campus - Quiz 1
vedasandeepb@gmail.com Switch account
 
Draft saved
* Indicates required question
Email
*
Record vedasandeepb@gmail.com as the email to be included with my response
Full Name

*
Veda Sandeep
SIC ID

*
SIC23951a12g9
Mobile Number

*
9848982758
Email ID

*
vedasandeepb@gmail.com
1. Create examples of zero vector, one vector, square matrix, diagonal matrix, identity matrix, and symmetric matrix one by one, and represent vectors and matrices with NumPy.

*
 
This is a required question
2. The shares of three companies A, B, and C are 1 million won, 800,000 won, and 500,000 won, respectively. We want to find the amount required to purchase 3, 4, and 5 shares of these stocks, respectively.

i)       Express the stocks’ price and quantity as p vector and n vector, respectively and coded with NumPy.


ii)       The amount required to purchase stocks is expressed by multiplication, and the value is calculated by Numpy operation.

*
 
This is a required question
3. When the following code is executed, all data of the MNIST numeric image is converted into vectors to create a single NumPy matrix X. Use this matrix to solve the following problem.

1)       Find the similarity between the first image and the tenth image using dot product.

2)       Find the similarity for a combination of all images using the dot product, how would it be efficient to implement it (hint: using matrices and multiplication of matrices)

*
Captionless Image
 
This is a required question
4. Calculate the following inverse matrix.

*
Captionless Image
 
This is a required question
5. The Boston house price problem is a problem of predicting the housing price of each town in Boston, USA using features such as the crime rate and air pollution in the area. It can be imported from the scikit-learn package. Find the weight vector x when the Boston house price problem is solved with the linear prediction model Ax=. Matrix and vector data can be obtained as follows.

Here, to simplify the problem, we limited the input data to crime rate (CRIM), air quality (NOX), number of rooms (RM), and age (AGE), and only four data were used.

Run the code below to check whether the magnitude or sign of the weight vector obtained from running the program is consistent the common notion. In order to find it, interpret the printed output for all the factors: CRIM, NOX, RM and AGE. 

(※ Write the interpreted output like “the house price is in inverse proportion to the crime rate (CRIM).”)

*
Captionless Image
6. Find the weight vector w when the Boston house price problem is solved with the linear prediction model X_w = y ̂ by the least-squares method. Matrix and vector data can be obtained as follows.

(※ This is the question related to question 5.) 

The meaning of each column of matrix X is as follows.

CRIM: crime rate

INDUS: Non-retail commercial area ratio

NOX: Nitric Oxide Concentration

RM: Number of rooms per house

LSTAT: Proportion of the lower class of the population

B: Proportion of black people in the population

PTRATIO: Student/Teacher Ratio

ZN: Percentage of residential areas exceeding 25,000 square feet

CHAS: 1 if located on the Charles River border, 0 otherwise

AGE: Percentage of houses built before 1940

RAD: Distance to radial highway

DIS: Weighted average distance to 5 Boston Job Centers

TAX: property tax rate

1)       Run the program above to check whether the magnitude or sign of the weight vector obtained from running the program is consistent the common notion. In order to find it, interpret the printed output for all the factors suggested above. 

(※ Write the interpreted output like “the house price is in inverse proportion to the crime rate (CRIM)”.)


2)       Explain how the result differs from the value obtained in Question 5.

*
Captionless Image
7. The ratings given by three users a, b, and c to 4 movies are expressed as vectors as follows.

1)       Find the Euclidean distance between a, b, and c. Which two users are the closest? And which two users are farthest apart?


2)       Find the cosine distance between a, b, and c. Which two users are the closest? And which two users are farthest apart?

*
Captionless Image
8. Find the eigenvalues of the following matrix using the characteristic equation.

*
Captionless Image
9. The log 2 value is about 0.69, and the  log 3 value is about 1.10. At this time, find the log 12 value. 

*
 
This is a required question
10. Find the inverse function of the logistic function.

*
Captionless Image
11. Differentiate the following functions. In this equation, k, a, and b are constants, not variables.

*
Captionless Image
*
Captionless Image
13. Find the derivative that differentiates the following function using SymPy. In this expression, k, a, and b are constants, not variables.
*
Captionless Image
*
Captionless Image
Page 1 of 1
Never submit passwords through Google Forms.
This form was created inside of Institute Of Aeronautical Engineering. - Contact form owner
Does this form look suspicious? Report

Google Forms
"""



'2. The shares of three companies A, B, and C are 1 million won, 800,000 won, and 500,000 won, respectively. We want to find the amount required to purchase 3, 4, and 5 shares of these stocks, respectively.\n\ni)       Express the stocks’ price and quantity as p vector and n vector, respectively and coded with NumPy.\n\n\nii)       The amount required to purchase stocks is expressed by multiplication, and the value is calculated by Numpy operation.\n\nSamsung Innovation Campus - Quiz 1\nvedasandeepb@gmail.com Switch account\n\nDraft saved\n* Indicates required question\nEmail\n*\nRecord vedasandeepb@gmail.com as the email to be included with my response\nFull Name\n\n*\nVeda Sandeep\nSIC ID\n\n*\nSIC23951a12g9\nMobile Number\n\n*\n9848982758\nEmail ID\n\n*\nvedasandeepb@gmail.com\n1. Create examples of zero vector, one vector, square matrix, diagonal matrix, identity matrix, and symmetric matrix one by one, and represent vectors and matrices with NumPy.\n\n*\n\nThis is a required quest